import Image from "next/image";
import { FiClock, FiImage, FiMusic } from "react-icons/fi";
import { getMemberResource } from "../member-api";
import { FlyerForm } from "./flyer-form";

type Song = { id: string; position: number; title: string; lyrics: string | null; musicalKey: string | null; notes: string | null };
type MinistryItem = { id: string; type: "PUBLICITY_FLYER" | "SONG_LIST"; title: string; instructions: string | null; status: string; deadlineAt: string | null; sentAt: string | null; createdAt: string; attachmentUrl: string | null; fileName: string | null; songs: Song[] };
type Overview = { canSubmitFlyer: boolean; mediaDepartment?: { id: string; name: string }; items: MinistryItem[] };
const formatter = new Intl.DateTimeFormat("en-GH", { dateStyle: "medium", timeStyle: "short", timeZone: "Africa/Accra" });

export default async function MediaHubPage() {
  const overview = await getMemberResource<Overview>("/ministry-content");
  return <main className="min-h-screen px-4 py-6 sm:px-6 lg:px-10 lg:py-9"><div className="mx-auto max-w-6xl">
    <header><p className="text-sm font-extrabold text-[#6b21a8]">Ministry collaboration</p><h1 className="mt-1 text-3xl font-black tracking-[-0.04em] sm:text-4xl">Media hub</h1><p className="mt-2 text-sm font-medium text-slate-500">Flyers and worship material shared with your ministry team.</p></header>
    {overview.canSubmitFlyer && <div className="mt-7"><FlyerForm /></div>}
    <section className="mt-8"><div className="flex items-end justify-between"><div><p className="text-sm font-extrabold text-[#6b21a8]">Shared work</p><h2 className="text-2xl font-black">Ministry material</h2></div><span className="text-sm font-bold text-slate-400">{overview.items.length} items</span></div>
      {overview.items.length === 0 ? <div className="mt-4 rounded-[2rem] border border-purple-100 bg-white p-12 text-center"><FiImage className="mx-auto text-3xl text-purple-300" /><p className="mt-3 font-black">No material shared yet</p></div> : <div className="mt-4 grid gap-5 lg:grid-cols-2">{overview.items.map((item) => item.type === "PUBLICITY_FLYER" ? <article className="overflow-hidden rounded-[1.75rem] border border-purple-100 bg-white shadow-sm" key={item.id}>{item.attachmentUrl ? <div className="relative aspect-[4/3] bg-purple-50"><Image alt={item.title} className="object-cover" fill sizes="(max-width: 1024px) 100vw, 50vw" src={item.attachmentUrl} unoptimized /></div> : null}<div className="p-5"><div className="flex items-start justify-between gap-3"><h3 className="font-black">{item.title}</h3><span className="rounded-full bg-lime-100 px-2 py-1 text-[10px] font-black text-lime-800">{item.status}</span></div>{item.instructions && <p className="mt-2 text-sm leading-6 text-slate-500">{item.instructions}</p>}<p className="mt-4 flex items-center gap-2 text-xs font-bold text-slate-400"><FiClock />{formatter.format(new Date(item.sentAt ?? item.createdAt))}</p>{item.attachmentUrl ? <a className="mt-4 inline-flex text-sm font-extrabold text-[#6b21a8]" href={item.attachmentUrl} rel="noreferrer" target="_blank">Open full flyer →</a> : null}</div></article> : <article className="rounded-[1.75rem] border border-purple-100 bg-white p-5 shadow-sm" key={item.id}><div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-purple-100 text-xl text-[#6b21a8]"><FiMusic /></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><h3 className="font-black">{item.title}</h3><span className="rounded-full bg-lime-100 px-2 py-1 text-[10px] font-black text-lime-800">{item.status}</span></div><p className="mt-1 flex items-center gap-2 text-xs font-bold text-slate-400"><FiClock />{formatter.format(new Date(item.sentAt ?? item.createdAt))}</p></div></div>{item.instructions ? <p className="mt-4 text-sm leading-6 text-slate-500">{item.instructions}</p> : null}<ol className="mt-4 divide-y divide-purple-50">{item.songs.map((song) => <li className="py-3" key={song.id}><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-xl bg-purple-50 text-xs font-black text-[#6b21a8]">{song.position}</span><p className="font-black">{song.title}</p>{song.musicalKey ? <span className="ml-auto text-xs font-black text-slate-500">Key {song.musicalKey}</span> : null}</div>{song.notes ? <p className="ml-11 mt-1 text-xs text-slate-500">{song.notes}</p> : null}{song.lyrics ? <details className="ml-11 mt-2"><summary className="cursor-pointer text-xs font-black text-[#6b21a8]">View lyrics</summary><p className="mt-2 whitespace-pre-wrap rounded-xl bg-purple-50 p-3 text-sm leading-6 text-slate-700">{song.lyrics}</p></details> : null}</li>)}</ol></article>)}</div>}
    </section>
  </div></main>;
}
