import Link from "next/link";
import { FiAlertCircle, FiArrowUpRight, FiCheckCircle, FiClock, FiImage, FiMusic } from "react-icons/fi";
import { AdminActionButton } from "@/components/admin-action-button";
import { getAdminResource } from "../registrations/admin-api";
import { advanceMinistryWork } from "./actions";

type Item = { id: string; type: string; title: string; instructions: string | null; status: string; deadlineAt: string | null; sentAt: string | null; acknowledgedAt: string | null; completedAt: string | null; createdAt: string; senderEmail: string; targetDepartment: string; attachmentUrl: string | null };
const formatter = new Intl.DateTimeFormat("en-GH", { dateStyle: "medium", timeStyle: "short", timeZone: "Africa/Accra" });

export default async function MinistryWorkPage() {
  const items = await getAdminResource<Item[]>("/admin/ministry-content");
  const newItems = items.filter((item) => item.status === "SENT");
  const active = items.filter((item) => item.status === "ACKNOWLEDGED");
  const completed = items.filter((item) => item.status === "COMPLETED");
  return <main className="min-h-screen bg-[#090a0d] px-5 py-8 text-slate-100"><div className="mx-auto max-w-7xl">
    <header><p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-400">Ministry operations</p><h1 className="mt-2 text-3xl font-bold">Shared work</h1><p className="mt-2 text-sm text-slate-400">Monitor Publicity, Choir, and Media handoffs and resolve stalled work.</p></header>
    <section className="mt-7 grid gap-3 sm:grid-cols-3"><Metric icon={FiAlertCircle} label="Awaiting Media" value={newItems.length} tone="amber" /><Metric icon={FiClock} label="In progress" value={active.length} tone="violet" /><Metric icon={FiCheckCircle} label="Completed" value={completed.length} tone="green" /></section>
    <section className="mt-7 space-y-3">{items.length ? items.map((item) => <article className="rounded-2xl border border-white/10 bg-[#111318] p-5" key={item.id}><div className="flex flex-wrap items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-violet-500/10 text-xl text-violet-300">{item.type === "PUBLICITY_FLYER" ? <FiImage /> : <FiMusic />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="font-bold text-white">{item.title}</h2><p className="mt-1 text-xs text-slate-500">From {item.senderEmail} → {item.targetDepartment}</p></div><Status status={item.status} /></div>{item.instructions ? <p className="mt-3 text-sm leading-6 text-slate-400">{item.instructions}</p> : null}<div className="mt-4 flex flex-wrap items-center gap-4 text-xs font-bold text-slate-500"><span>Sent {formatter.format(new Date(item.sentAt ?? item.createdAt))}</span>{item.deadlineAt ? <span className={new Date(item.deadlineAt) < new Date() && item.status !== "COMPLETED" ? "text-red-300" : ""}>Due {formatter.format(new Date(item.deadlineAt))}</span> : null}{item.attachmentUrl ? <Link className="inline-flex items-center gap-1 text-violet-300" href={item.attachmentUrl} target="_blank">Open asset <FiArrowUpRight /></Link> : null}</div>{["SENT", "ACKNOWLEDGED"].includes(item.status) ? <form action={advanceMinistryWork} className="mt-4"><input name="contentId" type="hidden" value={item.id} /><input name="action" type="hidden" value={item.status === "SENT" ? "ACKNOWLEDGE" : "COMPLETE"} /><AdminActionButton className="rounded-lg bg-violet-600 px-4 py-2 text-sm font-bold text-white" pendingLabel="Updating…">{item.status === "SENT" ? "Acknowledge for Media" : "Mark complete"}</AdminActionButton></form> : null}</div></div></article>) : <div className="rounded-2xl border border-dashed border-white/15 p-12 text-center text-slate-400">No ministry work has been shared yet.</div>}</section>
  </div></main>;
}

function Status({ status }: { status: string }) { const style = status === "COMPLETED" ? "bg-emerald-400/10 text-emerald-300" : status === "ACKNOWLEDGED" ? "bg-violet-400/10 text-violet-300" : "bg-amber-400/10 text-amber-300"; return <span className={`rounded-full px-3 py-1 text-[10px] font-bold ${style}`}>{status === "SENT" ? "AWAITING MEDIA" : status === "ACKNOWLEDGED" ? "IN PROGRESS" : status}</span>; }
function Metric({ icon: Icon, label, value, tone }: { icon: typeof FiClock; label: string; value: number; tone: "amber" | "violet" | "green" }) { const style = tone === "amber" ? "text-amber-300 bg-amber-400/10" : tone === "green" ? "text-emerald-300 bg-emerald-400/10" : "text-violet-300 bg-violet-400/10"; return <article className="rounded-2xl border border-white/10 bg-[#111318] p-5"><div className={`grid size-10 place-items-center rounded-xl ${style}`}><Icon /></div><p className="mt-4 text-3xl font-bold">{value}</p><p className="mt-1 text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p></article>; }
