import Link from "next/link";
import { FiArrowLeft, FiCheckCircle, FiMapPin, FiUserCheck } from "react-icons/fi";
import { getAdminResource } from "../../../registrations/admin-api";
import { correctAttendance, markManualAttendance } from "./actions";

type Member = { memberId: string; firstName: string; lastName: string; email: string; attendanceId: string | null; attendanceStatus: string | null; method: string | null; distanceMeters: number | null };
type Roster = { event: { id: string; name: string; status: string }; members: Member[] };

export default async function AttendanceRosterPage({ params }: { params: Promise<{ eventId: string }> }) {
  const { eventId } = await params;
  const roster = await getAdminResource<Roster>(`/attendance/events/${eventId}`);
  const attended = roster.members.filter((member) => member.attendanceId).length;
  const locked = roster.event.status === "CANCELLED";
  return <main className="min-h-screen bg-slate-50 px-5 py-8 text-slate-950"><div className="mx-auto max-w-7xl">
    <Link className="inline-flex items-center gap-2 font-bold text-[#6b21a8]" href={`/admin/events/${eventId}`}><FiArrowLeft aria-hidden="true" />Back to event</Link>
    <header className="mt-6 flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#6b21a8]">Event attendance</p><h1 className="mt-2 text-3xl font-bold">{roster.event.name}</h1><p className="mt-2 text-slate-600">{attended} of {roster.members.length} members have attendance records.</p></div><span className="bg-purple-50 px-3 py-1 text-xs font-bold text-[#6b21a8]">{roster.event.status}</span></header>
    <section className="mt-8 divide-y divide-slate-200 border-y border-slate-200 bg-white">{roster.members.map((member) => <article className="grid gap-4 px-5 py-5 lg:grid-cols-[minmax(14rem,1fr)_minmax(18rem,1.4fr)]" key={member.memberId}><div><h2 className="font-bold">{member.firstName} {member.lastName}</h2><p className="mt-1 text-sm text-slate-500">{member.email}</p>{member.attendanceId ? <div className="mt-3 flex flex-wrap items-center gap-3 text-sm"><span className="inline-flex items-center gap-2 bg-green-50 px-3 py-1 font-bold text-green-800"><FiCheckCircle aria-hidden="true" />{member.attendanceStatus?.replaceAll("_", " ")}</span><span className="text-slate-600">{member.method?.toLowerCase()}</span>{member.distanceMeters !== null ? <span className="inline-flex items-center gap-1 text-slate-500"><FiMapPin aria-hidden="true" />{member.distanceMeters.toFixed(1)} m</span> : null}</div> : <p className="mt-3 text-sm font-semibold text-amber-700">No attendance recorded</p>}</div>
      {!locked ? member.attendanceId ? <form action={correctAttendance} className="grid gap-2 sm:grid-cols-[10rem_1fr_auto]"><input name="eventId" type="hidden" value={eventId} /><input name="attendanceId" type="hidden" value={member.attendanceId} /><select className="h-10 rounded-lg border border-slate-300 bg-white px-3" defaultValue={member.attendanceStatus ?? "ON_TIME"} name="status"><option value="EARLY">Early</option><option value="ON_TIME">On time</option><option value="LATE">Late</option><option value="ABSENT">Absent</option><option value="EXCUSED">Excused</option></select><input className="h-10 min-w-0 rounded-lg border border-slate-300 px-3" minLength={3} name="reviewNote" placeholder="Reason for correction" required /><button className="h-10 rounded-lg border border-[#6b21a8] px-4 font-bold text-[#6b21a8]" type="submit">Correct</button></form> : <form action={markManualAttendance} className="grid gap-2 sm:grid-cols-[10rem_1fr_auto]"><input name="eventId" type="hidden" value={eventId} /><input name="memberId" type="hidden" value={member.memberId} /><select className="h-10 rounded-lg border border-slate-300 bg-white px-3" name="status"><option value="ON_TIME">On time</option><option value="EARLY">Early</option><option value="LATE">Late</option></select><input className="h-10 min-w-0 rounded-lg border border-slate-300 px-3" minLength={3} name="reason" placeholder="Manual attendance reason" required /><button className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#240046] px-4 font-bold text-white" type="submit"><FiUserCheck aria-hidden="true" />Mark</button></form> : <p className="text-sm text-slate-500">Cancelled event records are read-only.</p>}
    </article>)}</section>
  </div></main>;
}
